BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "particule" (
	"PA_NUM"	INTEGER,
	"PA_NOM"	INTEGER,
	"PA_M"	INTEGER,
	"PA_R"	INTEGER
);
CREATE TABLE IF NOT EXISTS "rebond" (
	"SI_NUM"	INTEGER,
	"RE_NUM"	INTEGER,
	"PA_NUM"	INTEGER,
	"RE_T"	INTEGER,
	"RE_DIR"	INTEGER,
	"RE_VIT"	INTEGER,
	"RE_P"	INTEGER
);
CREATE TABLE IF NOT EXISTS "simulation" (
	"SI_NUM"	INTEGER,
	"SI_DEB"	INTEGER,
	"SI_DUR"	INTEGER,
	"SI_DIM"	INTEGER,
	"SI_N"	INTEGER,
	"SI_L"	INTEGER
);
CREATE TABLE IF NOT EXISTS "demographie" (
	"pays"	TEXT,
	"periode"	INTEGER,
	"pop"	INTEGER
);
CREATE TABLE IF NOT EXISTS "palu" (
	"nom"	TEXT,
	"iso"	TEXT,
	"annee"	INTEGER,
	"cas"	INTEGER,
	"deces"	INTEGER
);
INSERT INTO "demographie" VALUES ('BR',2009,193020000);
INSERT INTO "demographie" VALUES ('KE',2010,40909000);
INSERT INTO "demographie" VALUES ('ML',2011,14417000);
INSERT INTO "demographie" VALUES ('UG',2010,33987000);
INSERT INTO "demographie" VALUES ('BR',2010,194946000);
INSERT INTO "demographie" VALUES (NULL,NULL,NULL);
INSERT INTO "palu" VALUES ('Bresil','BR',2010,334667,76);
INSERT INTO "palu" VALUES ('Kenya','KE',2010,898667,26017);
INSERT INTO "palu" VALUES ('Mali','ML',2011,307035,2128);
INSERT INTO "palu" VALUES ('Ouganda','UG',2010,1581160,8431);
INSERT INTO "palu" VALUES ('Bresil','BR',2009,309316,85);
COMMIT;
